/**
 * Mock Data - Seed data for demo / Demo üçün test məlumatları
 */

import { Topic, Lesson } from '@/store/learnStore';
import { Question } from '@/store/simulatorStore';
import { Package } from '@/store/packagesStore';

// Topics / Mövzular
export const mockTopics: Topic[] = [
  {
    id: '1',
    title: 'Yol Hərəkəti Qaydaları',
    titleEn: 'Traffic Rules',
    titleRu: 'Правила дорожного движения',
    lessonCount: 3,
    completedLessons: 0,
    iconName: 'traffic-light',
  },
  {
    id: '2',
    title: 'Yol Nişanları',
    titleEn: 'Road Signs',
    titleRu: 'Дорожные знаки',
    lessonCount: 2,
    completedLessons: 0,
    iconName: 'sign',
  },
  {
    id: '3',
    title: 'Avtomobilin Texniki Vəziyyəti',
    titleEn: 'Vehicle Technical Condition',
    titleRu: 'Техническое состояние автомобиля',
    lessonCount: 2,
    completedLessons: 0,
    iconName: 'car',
  },
  {
    id: '4',
    title: 'İlk Tibbi Yardım',
    titleEn: 'First Aid',
    titleRu: 'Первая помощь',
    lessonCount: 1,
    completedLessons: 0,
    iconName: 'medical',
  },
];

// Lessons / Dərslər
export const mockLessons: Lesson[] = [
  {
    id: 'l1',
    topicId: '1',
    title: 'Piyada Keçidi Qaydaları',
    titleEn: 'Pedestrian Crossing Rules',
    titleRu: 'Правила пешеходного перехода',
    duration: 320,
    videoUrl: 'https://example.com/lesson1.mp4',
    thumbnailUrl: 'https://via.placeholder.com/400x225/10B981/FFFFFF?text=Lesson+1',
    keyPoints: [
      'Piyada keçidində dayanmaq məcburidir',
      'Hər iki tərəfə baxın',
      'Piyadaların keçid hüququ var',
    ],
    completed: false,
    downloaded: false,
    progress: 0,
  },
  {
    id: 'l2',
    topicId: '1',
    title: 'Sürət Məhdudiyyətləri',
    titleEn: 'Speed Limits',
    titleRu: 'Ограничения скорости',
    duration: 280,
    videoUrl: 'https://example.com/lesson2.mp4',
    thumbnailUrl: 'https://via.placeholder.com/400x225/059669/FFFFFF?text=Lesson+2',
    keyPoints: [
      'Şəhərdə 60 km/saat',
      'Kənarda 90 km/saat',
      'Avtomaqistralda 110 km/saat',
    ],
    completed: false,
    downloaded: false,
    progress: 0,
  },
  {
    id: 'l3',
    topicId: '1',
    title: 'Manevr Qaydaları',
    titleEn: 'Maneuver Rules',
    titleRu: 'Правила маневрирования',
    duration: 360,
    videoUrl: 'https://example.com/lesson3.mp4',
    thumbnailUrl: 'https://via.placeholder.com/400x225/34D399/FFFFFF?text=Lesson+3',
    keyPoints: [
      'Siqnal vermək lazımdır',
      'Arxa görüş güzgüsünə baxın',
      'Təhlükəsiz manevr edin',
    ],
    completed: false,
    downloaded: false,
    progress: 0,
  },
  {
    id: 'l4',
    topicId: '2',
    title: 'Qadağan Edici Nişanlar',
    titleEn: 'Prohibitory Signs',
    titleRu: 'Запрещающие знаки',
    duration: 240,
    videoUrl: 'https://example.com/lesson4.mp4',
    thumbnailUrl: 'https://via.placeholder.com/400x225/EF4444/FFFFFF?text=Lesson+4',
    keyPoints: [
      'Qırmızı dairəvi nişanlar',
      'Daxil olmaq qadağandır',
      'Sürət məhdudiyyəti',
    ],
    completed: false,
    downloaded: false,
    progress: 0,
  },
  {
    id: 'l5',
    topicId: '2',
    title: 'Məcburi Nişanlar',
    titleEn: 'Mandatory Signs',
    titleRu: 'Предписывающие знаки',
    duration: 220,
    videoUrl: 'https://example.com/lesson5.mp4',
    thumbnailUrl: 'https://via.placeholder.com/400x225/3B82F6/FFFFFF?text=Lesson+5',
    keyPoints: [
      'Mavi dairəvi nişanlar',
      'İstiqamət göstərir',
      'Yerinə yetirilməsi məcburidir',
    ],
    completed: false,
    downloaded: false,
    progress: 0,
  },
  {
    id: 'l6',
    topicId: '3',
    title: 'Əyləc Sistemi',
    titleEn: 'Brake System',
    titleRu: 'Тормозная система',
    duration: 300,
    videoUrl: 'https://example.com/lesson6.mp4',
    thumbnailUrl: 'https://via.placeholder.com/400x225/F59E0B/FFFFFF?text=Lesson+6',
    keyPoints: [
      'Əyləc mayelini yoxlayın',
      'Əyləc disklərinin vəziyyəti',
      'ABS sistemi',
    ],
    completed: false,
    downloaded: false,
    progress: 0,
  },
  {
    id: 'l7',
    topicId: '3',
    title: 'İşıqlandırma Sistemi',
    titleEn: 'Lighting System',
    titleRu: 'Система освещения',
    duration: 180,
    videoUrl: 'https://example.com/lesson7.mp4',
    thumbnailUrl: 'https://via.placeholder.com/400x225/8B5CF6/FFFFFF?text=Lesson+7',
    keyPoints: [
      'Faralar və işıqlar',
      'Duman faraları',
      'Siqnal işıqları',
    ],
    completed: false,
    downloaded: false,
    progress: 0,
  },
  {
    id: 'l8',
    topicId: '4',
    title: 'Qanaxmanı Dayandırma',
    titleEn: 'Stopping Bleeding',
    titleRu: 'Остановка кровотечения',
    duration: 420,
    videoUrl: 'https://example.com/lesson8.mp4',
    thumbnailUrl: 'https://via.placeholder.com/400x225/EC4899/FFFFFF?text=Lesson+8',
    keyPoints: [
      'Təzyiq nöqtəsi',
      'Turniket istifadəsi',
      'Təcili yardım çağırın',
    ],
    completed: false,
    downloaded: false,
    progress: 0,
  },
];

// Questions / Suallar
export const mockQuestions: Question[] = [
  {
    id: 'q1',
    text: 'Şəhərdaxili yollarda maksimum icazə verilən sürət neçə km/saat-dır?',
    textEn: 'What is the maximum speed limit in urban areas?',
    textRu: 'Какова максимальная скорость в городских зонах?',
    options: ['50 km/saat', '60 km/saat', '70 km/saat', '80 km/saat'],
    optionsEn: ['50 km/h', '60 km/h', '70 km/h', '80 km/h'],
    optionsRu: ['50 км/ч', '60 км/ч', '70 км/ч', '80 км/ч'],
    correctIndex: 1,
    explanation: 'Şəhərdaxili yollarda maksimum sürət 60 km/saat-dır.',
    explanationEn: 'The maximum speed in urban areas is 60 km/h.',
    explanationRu: 'Максимальная скорость в городских зонах составляет 60 км/ч.',
    category: 'rules',
  },
  {
    id: 'q2',
    text: 'Piyada keçidində hansı nəqliyyat vasitəsi üstünlük hüququna malikdir?',
    textEn: 'Who has right of way at pedestrian crossings?',
    textRu: 'Кто имеет право проезда на пешеходных переходах?',
    options: ['Avtomobil', 'Piyada', 'Velosiped', 'Motosiklet'],
    optionsEn: ['Car', 'Pedestrian', 'Bicycle', 'Motorcycle'],
    optionsRu: ['Автомобиль', 'Пешеход', 'Велосипед', 'Мотоцикл'],
    correctIndex: 1,
    explanation: 'Piyada keçidində piyadalar üstünlük hüququna malikdir.',
    explanationEn: 'Pedestrians have right of way at pedestrian crossings.',
    explanationRu: 'Пешеходы имеют право проезда на пешеходных переходах.',
    category: 'rules',
  },
  {
    id: 'q3',
    text: 'Qırmızı işıq yananda nə etməlisiniz?',
    textEn: 'What should you do at a red light?',
    textRu: 'Что делать на красный свет?',
    options: ['Davam etmək', 'Dayanmaq', 'Yavaşlamaq', 'Siqnal vermək'],
    optionsEn: ['Continue', 'Stop', 'Slow down', 'Signal'],
    optionsRu: ['Продолжать', 'Остановиться', 'Замедлить', 'Сигналить'],
    correctIndex: 1,
    explanation: 'Qırmızı işıqda tam dayanmalısınız.',
    explanationEn: 'You must come to a complete stop at a red light.',
    explanationRu: 'На красный свет необходимо полностью остановиться.',
    category: 'signals',
  },
  {
    id: 'q4',
    text: 'Təhlükəsizlik kəməri nə vaxt taxılmalıdır?',
    textEn: 'When should you wear a seatbelt?',
    textRu: 'Когда нужно пристегивать ремень безопасности?',
    options: ['Yalnız şəhərdə', 'Yalnız yol kənarında', 'Həmişə', 'Yalnız gecə'],
    optionsEn: ['Only in city', 'Only on highway', 'Always', 'Only at night'],
    optionsRu: ['Только в городе', 'Только на трассе', 'Всегда', 'Только ночью'],
    correctIndex: 2,
    explanation: 'Təhlükəsizlik kəməri həmişə taxılmalıdır.',
    explanationEn: 'Seatbelts must be worn at all times.',
    explanationRu: 'Ремень безопасности нужно пристегивать всегда.',
    category: 'safety',
  },
  {
    id: 'q5',
    text: 'Dönüş edərkən hansı siqnal verilməlidir?',
    textEn: 'Which signal should be given when turning?',
    textRu: 'Какой сигнал подавать при повороте?',
    options: ['Səs siqnalı', 'İstiqamət göstərici', 'Uzaq işıq', 'Yaxın işıq'],
    optionsEn: ['Horn', 'Turn signal', 'High beam', 'Low beam'],
    optionsRu: ['Гудок', 'Поворотник', 'Дальний свет', 'Ближний свет'],
    correctIndex: 1,
    explanation: 'Dönüş edərkən istiqamət göstərici siqnalı verilməlidir.',
    explanationEn: 'Turn signals must be used when turning.',
    explanationRu: 'При повороте необходимо использовать поворотники.',
    category: 'maneuver',
  },
  {
    id: 'q6',
    text: 'Avtomaqistralda maksimum sürət neçədir?',
    textEn: 'What is the maximum speed on highways?',
    textRu: 'Какая максимальная скорость на автомагистрали?',
    options: ['90 km/saat', '100 km/saat', '110 km/saat', '120 km/saat'],
    optionsEn: ['90 km/h', '100 km/h', '110 km/h', '120 km/h'],
    optionsRu: ['90 км/ч', '100 км/ч', '110 км/ч', '120 км/ч'],
    correctIndex: 2,
    explanation: 'Avtomaqistralda maksimum sürət 110 km/saat-dır.',
    explanationEn: 'The maximum speed on highways is 110 km/h.',
    explanationRu: 'Максимальная скорость на автомагистрали 110 км/ч.',
    category: 'rules',
  },
  {
    id: 'q7',
    text: 'Park edərkən təkərlər hansı tərəfə çevrilməlidir?',
    textEn: 'Which way should wheels be turned when parking?',
    textRu: 'В какую сторону поворачивать колеса при парковке?',
    options: ['Sola', 'Düz', 'Yamaca görə', 'Sağa'],
    optionsEn: ['Left', 'Straight', 'Depends on slope', 'Right'],
    optionsRu: ['Налево', 'Прямо', 'Зависит от склона', 'Направо'],
    correctIndex: 2,
    explanation: 'Park edərkən təkərlər yamacın istiqamətinə görə çevrilməlidir.',
    explanationEn: 'Wheels should be turned according to the slope when parking.',
    explanationRu: 'При парковке колеса поворачивают в зависимости от склона.',
    category: 'parking',
  },
  {
    id: 'q8',
    text: 'Duman olduqda hansı işıqlar yandırılmalıdır?',
    textEn: 'Which lights should be used in fog?',
    textRu: 'Какие фары использовать в тумане?',
    options: ['Uzaq işıq', 'Duman faraları', 'Heç biri', 'Fəhlə işığı'],
    optionsEn: ['High beam', 'Fog lights', 'None', 'Work light'],
    optionsRu: ['Дальний свет', 'Противотуманные фары', 'Никакие', 'Рабочий свет'],
    correctIndex: 1,
    explanation: 'Duman olduqda duman faraları yandırılmalıdır.',
    explanationEn: 'Fog lights should be used in foggy conditions.',
    explanationRu: 'В тумане нужно использовать противотуманные фары.',
    category: 'lights',
  },
  {
    id: 'q9',
    text: 'Qanaxma zamanı ilk olaraq nə edilməlidir?',
    textEn: 'What should be done first in case of bleeding?',
    textRu: 'Что делать в первую очередь при кровотечении?',
    options: ['Təcili yardım çağırın', 'Yaranı yuyun', 'Təzyiq tətbiq edin', 'Yatırın'],
    optionsEn: ['Call ambulance', 'Wash wound', 'Apply pressure', 'Lay down'],
    optionsRu: ['Вызвать скорую', 'Промыть рану', 'Надавить', 'Уложить'],
    correctIndex: 2,
    explanation: 'Qanaxmada ilk olaraq yara yerinə təzyiq tətbiq edilməlidir.',
    explanationEn: 'Pressure should be applied to the wound first in case of bleeding.',
    explanationRu: 'При кровотечении сначала нужно надавить на рану.',
    category: 'first-aid',
  },
  {
    id: 'q10',
    text: 'İkiqat səslə xəttini keçmək nə vaxt icazəlidir?',
    textEn: 'When is it allowed to cross a double solid line?',
    textRu: 'Когда можно пересекать двойную сплошную линию?',
    options: ['Həmişə', 'Heç vaxt', 'Təcili hallarda', 'Gecələr'],
    optionsEn: ['Always', 'Never', 'In emergencies', 'At night'],
    optionsRu: ['Всегда', 'Никогда', 'В экстренных случаях', 'Ночью'],
    correctIndex: 1,
    explanation: 'İkiqat səslə xəttini heç vaxt keçmək olmaz.',
    explanationEn: 'It is never allowed to cross a double solid line.',
    explanationRu: 'Двойную сплошную линию пересекать никогда нельзя.',
    category: 'markings',
  },
  // Add 20 more questions for robust testing
  {
    id: 'q11',
    text: 'Təkər təzyiqi nə vaxt yoxlanılmalıdır?',
    textEn: 'When should tire pressure be checked?',
    textRu: 'Когда проверять давление в шинах?',
    options: ['Ayda bir dəfə', 'İldə bir dəfə', 'Hər gün', 'Heç vaxt'],
    optionsEn: ['Monthly', 'Yearly', 'Daily', 'Never'],
    optionsRu: ['Раз в месяц', 'Раз в год', 'Каждый день', 'Никогда'],
    correctIndex: 0,
    explanation: 'Təkər təzyiqi ən azı ayda bir dəfə yoxlanılmalıdır.',
    explanationEn: 'Tire pressure should be checked at least monthly.',
    explanationRu: 'Давление в шинах нужно проверять минимум раз в месяц.',
    category: 'maintenance',
  },
  {
    id: 'q12',
    text: 'Yağış zamanı görünüş məsafəsi azaldıqda nə edilməlidir?',
    textEn: 'What should be done when visibility decreases in rain?',
    textRu: 'Что делать когда видимость снижается в дождь?',
    options: ['Sürəti artırın', 'Sürəti azaldın', 'Dayanın', 'Siqnal verin'],
    optionsEn: ['Increase speed', 'Reduce speed', 'Stop', 'Signal'],
    optionsRu: ['Увеличить скорость', 'Снизить скорость', 'Остановиться', 'Сигналить'],
    correctIndex: 1,
    explanation: 'Görünüş azaldıqda sürəti azaltmaq lazımdır.',
    explanationEn: 'Speed should be reduced when visibility decreases.',
    explanationRu: 'При снижении видимости нужно уменьшить скорость.',
    category: 'weather',
  },
];

// Packages / Paketlər
export const mockPackages: Package[] = [
  {
    id: 'free',
    name: 'Pulsuz',
    nameEn: 'Free',
    nameRu: 'Бесплатный',
    price: 0,
    currency: 'AZN',
    duration: 'monthly',
    features: [
      '5 dərs',
      '3 test gündə',
      'Reklam var',
      'Əsas material',
    ],
    featuresEn: [
      '5 lessons',
      '3 tests per day',
      'With ads',
      'Basic material',
    ],
    featuresRu: [
      '5 уроков',
      '3 теста в день',
      'С рекламой',
      'Базовый материал',
    ],
  },
  {
    id: 'standard',
    name: 'Standart',
    nameEn: 'Standard',
    nameRu: 'Стандартный',
    price: 9.99,
    priceMonthly: 9.99,
    currency: 'AZN',
    duration: 'monthly',
    popular: true,
    features: [
      'Bütün dərslər',
      'Limitsiz testlər',
      'Reklamsız',
      'Offline rejim',
      'PDF kitablar',
    ],
    featuresEn: [
      'All lessons',
      'Unlimited tests',
      'Ad-free',
      'Offline mode',
      'PDF books',
    ],
    featuresRu: [
      'Все уроки',
      'Безлимитные тесты',
      'Без рекламы',
      'Офлайн режим',
      'PDF книги',
    ],
    stripePriceId: 'price_standard_monthly',
  },
  {
    id: 'premium',
    name: 'Premium',
    nameEn: 'Premium',
    nameRu: 'Премиум',
    price: 89.99,
    priceMonthly: 7.49,
    currency: 'AZN',
    duration: 'yearly',
    features: [
      'Standart + ...',
      'Prioritet dəstək',
      'Müəllim rejimi',
      '3D video dərslər',
      'Şəxsi statistika',
      'Sertifikat',
    ],
    featuresEn: [
      'Standard + ...',
      'Priority support',
      'Teacher mode',
      '3D video lessons',
      'Personal stats',
      'Certificate',
    ],
    featuresRu: [
      'Стандарт + ...',
      'Приоритетная поддержка',
      'Режим учителя',
      '3D видео уроки',
      'Личная статистика',
      'Сертификат',
    ],
    stripePriceId: 'price_premium_yearly',
  },
];
