export const roadSignsData = [
  // Warning Signs (Xəbərdarlıq nişanları)
  {
    id: 'w1',
    code: '1.1',
    name: 'Təhlükəli döngə',
    category: 'warning',
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/3/3a/Zeichen_103-10.svg/240px-Zeichen_103-10.svg.png',
    meaning: 'Qarşıda sağa təhlükəli döngə olduğunu bildirir. Sürücü sürətini azaltmalı və ehtiyatlı olmalıdır.',
    application: 'Təhlükəli əyilmələrdən 150-300 metr əvvəl qoyulur.',
    specialCases: 'Yağışlı havada və gecə vaxtı xüsusilə diqqətli olmaq lazımdır.',
    examImportance: 'high',
    commonMistake: true,
    detailedDescription: 'Təhlükəli döngə nişanı, yolda gözlənilməz və kəskin dönüşlərin olduğunu göstərir. Sürücülər bu nişanı görəndə sürətlərini azaltmalı və qarşıdan gələn nəqliyyat vasitələrinə diqqət etməlidirlər.\n\nDöngə hissəsində xəttə çıxmaq və yüksək sürətlə hərəkət etmək qəzaya səbəb ola bilər.'
  },
  {
    id: 'w2',
    code: '1.2',
    name: 'Təhlükəli əyilmələr',
    category: 'warning',
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/2/24/Zeichen_105-20.svg/240px-Zeichen_105-20.svg.png',
    meaning: 'Qarşıda bir-birini əvəz edən təhlükəli əyilmələr olduğunu bildirir.',
    application: 'İlk əyilməyə 150-300 metr qalmış qoyulur.',
    specialCases: 'Hər əyilmədə sürət yenidən azaldılmalıdır.',
    examImportance: 'high',
    commonMistake: false,
    detailedDescription: 'Bu nişan ardıcıl olaraq gələn təhlükəli dönüşlər haqqında xəbərdarlıq edir. Sürücü hər dönüşdə ayrıca ehtiyatlı olmalı və zolaqdan çıxmamalıdır.'
  },
  {
    id: 'w3',
    code: '1.5',
    name: 'Yol işləri',
    category: 'warning',
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/d/d1/Italy_traffic_signs_-_lavori_in_corso.svg/240px-Italy_traffic_signs_-_lavori_in_corso.svg.png',
    meaning: 'Qarşıda yol təmiri və ya tikinti işləri olduğunu bildirir.',
    application: 'Yol işləri başlanğıcından 50-100 metr əvvəl.',
    specialCases: 'İşçilərin hərəkətinə və əlavə nişanlara diqqət edin.',
    examImportance: 'medium',
    commonMistake: false,
    detailedDescription: 'Yol işləri aparılan ərazilərdə sürət məhdudiyyətinə riayət edilməli, işçilərə və texnikaya diqqət yetirilməlidir.'
  },
  {
    id: 'w4',
    code: '1.8',
    name: 'İşıqfor tənzimlənməsi',
    category: 'warning',
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/1/1e/Italy_traffic_signs_-_semaforo.svg/240px-Italy_traffic_signs_-_semaforo.svg.png',
    meaning: 'Qarşıda işıqforla tənzimlənən yol hissəsi olduğunu bildirir.',
    application: 'İşıqfordan 150-300 metr əvvəl qoyulur.',
    specialCases: 'Qırmızı işıqda mütləq dayanmaq lazımdır.',
    examImportance: 'high',
    commonMistake: true,
    detailedDescription: 'İşıqfor nişanı sürücünü qarşıda nizamlanmış kəsişmə olduğu barədə xəbərdar edir. Sarı işıq yananda sürət azaldılmalı və dayanmağa hazır olmaq lazımdır.'
  },
  {
    id: 'w5',
    code: '1.11',
    name: 'Piyada keçidi',
    category: 'warning',
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/5/54/Italian_traffic_signs_-_attraversamento_pedonale.svg/240px-Italian_traffic_signs_-_attraversamento_pedonale.svg.png',
    meaning: 'Qarşıda piyada keçidi olduğunu bildirir.',
    application: 'Piyada keçidindən 50-100 metr əvvəl.',
    specialCases: 'Piyadalara yol vermək məcburidir.',
    examImportance: 'high',
    commonMistake: true,
    detailedDescription: 'Piyada keçidi yaxınlığında sürət azaldılmalı və yolu keçən piyadalara mütləq üstünlük verilməlidir. Keçiddə dayanmaq qadağandır.'
  },
  {
    id: 'w6',
    code: '1.23',
    name: 'Uşaqlar',
    category: 'warning',
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/3/36/Zeichen_136-10.svg/240px-Zeichen_136-10.svg.png',
    meaning: 'Yolun uşaq müəssisələrinin (məktəb, bağça və s.) yaxınlığından keçdiyini bildirir.',
    application: 'Məktəb və bağçaların yaxınlığında.',
    specialCases: 'Uşaqların yola qəfil çıxma ehtimalı yüksəkdir.',
    examImportance: 'high',
    commonMistake: true,
    detailedDescription: 'Bu nişan sürücüləri ərazidə uşaqların ola biləcəyi barədə xəbərdar edir. Sürət azaldılmalı və hər an dayanmağa hazır olunmalıdır.'
  },
  {
    id: 'w7',
    code: '1.26',
    name: 'Vəhşi heyvanlar',
    category: 'warning',
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/1/13/Zeichen_142.svg/240px-Zeichen_142.svg.png',
    meaning: 'Yolda vəhşi heyvanların çıxma ehtimalının olduğunu bildirir.',
    application: 'Meşə zolaqları və qoruqların ərazisindən keçən yollarda.',
    specialCases: 'Gecə vaxtı heyvanların gözləri işığa həssas olur, diqqətli olun.',
    examImportance: 'medium',
    commonMistake: false,
    detailedDescription: 'Meşəlik ərazilərdə vəhşi heyvanların yola çıxması qəza riski yaradır. Bu nişan olan ərazidə sürət həddini aşmaq təhlükəlidir.'
  },

  // Priority Signs (Üstünlük nişanları)
  {
    id: 'p1',
    code: '2.1',
    name: 'Əsas yol',
    category: 'priority',
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/9/9e/Zeichen_306.svg/240px-Zeichen_306.svg.png',
    meaning: 'Bu nişan sürücüyə yolda üstünlük hüququ verir.',
    application: 'Əsas yolun başlanğıcında və kəsişmələr öncəsi.',
    specialCases: 'Digər yollardan gələn nəqliyyat vasitələri sizə yol verməlidir.',
    examImportance: 'high',
    commonMistake: false,
    detailedDescription: 'Əsas yol nişanı olan yolda hərəkət edən nəqliyyat vasitələri, digər yollardan daxil olan vasitələrə nisbətən üstünlüyə malikdir. Ancaq piyadalara üstünlük vermək məcburidir.'
  },
  {
    id: 'p2',
    code: '2.2',
    name: 'Əsas yolun sonu',
    category: 'priority',
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/8/8a/Zeichen_307.svg/240px-Zeichen_307.svg.png',
    meaning: 'Əsas yolun bitdiyini və üstünlük hüququnun aradan getdiyini bildirir.',
    application: 'Əsas yolun sona çatdığı yerdə.',
    specialCases: 'Növbəti kəsişmədə "Yol ver" qaydalarına əməl edin.',
    examImportance: 'high',
    commonMistake: false,
    detailedDescription: 'Bu nişandan sonra sürücü artıq üstünlük hüququ olmadığını bilməli və digər yollardan gələn vasitələrə diqqət etməlidir.'
  },
  {
    id: 'p3',
    code: '2.4',
    name: 'Yol ver',
    category: 'priority',
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/c/c8/Zeichen_205.svg/240px-Zeichen_205.svg.png',
    meaning: 'Qarşıdan və sağdan gələn nəqliyyat vasitələrinə yol verməyi tələb edir.',
    application: 'Kəsişmələrdə, əsas yola çıxış yerlərində.',
    specialCases: 'Dayanmaq məcburi deyil, amma sürət azaldılmalı və üstünlük verilməlidir.',
    examImportance: 'high',
    commonMistake: true,
    detailedDescription: 'Yol ver nişanı üçbucaq formalıdır və sürücüdən digər vasitələrə prioritet verməyi tələb edir. Təhlükə yaranmazsa dayanmadan da keçmək olar.'
  },
  {
    id: 'p4',
    code: '2.5',
    name: 'Hərəkət dayanmadan qadağandır',
    category: 'priority',
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/f/f9/Zeichen_206.svg/240px-Zeichen_206.svg.png',
    meaning: 'Mütləq dayanıb, digər vasitələrə yol verməyi tələb edir.',
    application: 'Təhlükəli kəsişmələrdə, görünməyən yol bağlantılarında.',
    specialCases: 'Hətta yol boş olsa belə, tam dayandıqdan sonra davam edin.',
    examImportance: 'high',
    commonMistake: true,
    detailedDescription: 'STOP nişanı görünəndə sürücü mütləq tam dayanmalı və yalnız təhlükə olmadığından əmin olduqdan sonra hərəkətə davam etməlidir.'
  },

  // Prohibitory Signs (Qadağan nişanları)
  {
    id: 'pr1',
    code: '3.1',
    name: 'Hərəkət qadağandır',
    category: 'prohibitory',
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/6/6e/Zeichen_250.svg/240px-Zeichen_250.svg.png',
    meaning: 'Bütün nəqliyyat vasitələrinin hərəkəti qadağandır.',
    application: 'Bağlı yollarda, təmir zamanı, xüsusi ərazilərdə.',
    specialCases: 'Yalnız xüsusi icazəsi olan vasitələr keçə bilər.',
    examImportance: 'high',
    commonMistake: false,
    detailedDescription: 'Bu nişan qırmızı dairə ilə göstərilir və heç bir nəqliyyat vasitəsinin hərəkətinə icazə vermir. Təcili yardım, yanğınsöndürmə və polis maşınları istisna ola bilər.'
  },
  {
    id: 'pr2',
    code: '3.2',
    name: 'Mexaniki nəqliyyat vasitələrinin hərəkəti qadağandır',
    category: 'prohibitory',
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/8/8d/Zeichen_260.svg/240px-Zeichen_260.svg.png',
    meaning: 'Avtomobildə və digər mexaniki vasitələrin hərəkəti qadağandır.',
    application: 'Piyada zonaları, parklar, xüsusi ərazilər.',
    specialCases: 'Velosiped və at arabaları keçə bilər.',
    examImportance: 'medium',
    commonMistake: false,
    detailedDescription: 'Mühərrikli nəqliyyat vasitələri daxil ola bilməz, lakin velosipedlər və digər mexaniki olmayan vasitələr keçə bilər.'
  },
  {
    id: 'pr3',
    code: '3.4',
    name: 'Yük avtomobillərinin hərəkəti qadağandır',
    category: 'prohibitory',
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/9/9e/Zeichen_253.svg/240px-Zeichen_253.svg.png',
    meaning: '3.5 tondan çox yük avtomobilinin hərəkəti qadağandır.',
    application: 'Şəhər mərkəzləri, yaşayış məhəllələri.',
    specialCases: 'Yüngül yük maşınları keçə bilər.',
    examImportance: 'medium',
    commonMistake: false,
    detailedDescription: 'Müəyyən edilmiş tonajdan çox yük maşınının hərəkətinə qadağa qoyur. Yaşayış bölgələrinin qorunması məqsədilə istifadə olunur.'
  },
  {
    id: 'pr4',
    code: '3.20',
    name: 'Ötmə qadağandır',
    category: 'prohibitory',
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/9/92/Zeichen_276.svg/240px-Zeichen_276.svg.png',
    meaning: 'Bütün növ nəqliyyat vasitələrini ötmək qadağandır.',
    application: 'Təhlükəli yol hissələrində, görünməyən döngələrdə.',
    specialCases: 'Motorsiklet, velosiped və at arabası ötmək olar.',
    examImportance: 'high',
    commonMistake: true,
    detailedDescription: 'Ötmə qadağası yol şərtlərinin təhlükəli olduğu yerlərdə qoyulur. Pozulması ağır qəzalara səbəb ola bilər.'
  },
  {
    id: 'pr5',
    code: '3.24',
    name: 'Sürət məhdudiyyəti',
    category: 'prohibitory',
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/5/56/Zeichen_274-56.svg/240px-Zeichen_274-56.svg.png',
    meaning: 'Maksimum icazə verilən sürəti göstərir (məs: 50 km/saat).',
    application: 'Şəhər, yaşayış məhəllələri, təhlükəli yollar.',
    specialCases: 'Göstərilən sürətdən artıq getmək qadağandır.',
    examImportance: 'high',
    commonMistake: true,
    detailedDescription: 'Sürət məhdudiyyətinə riayət təhlükəsizlik üçün vacibdir. Radar ilə nəzarət edilir və cərimə tətbiq olunur.'
  },
  {
    id: 'pr6',
    code: '3.27',
    name: 'Dayanma və durmaq qadağandır',
    category: 'prohibitory',
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/b/b0/Zeichen_283.svg/240px-Zeichen_283.svg.png',
    meaning: 'Bu nişan olan yerdə nəqliyyat vasitəsinin dayanıb durmaq qadağandır.',
    application: 'Dar yollar, körpülər, tunellər, kəsişmələr.',
    specialCases: 'Təcili hal istisnadır (qəza, xəstəlik).',
    examImportance: 'high',
    commonMistake: true,
    detailedDescription: 'Dayanma və durmaq qadağası yolun keçidini təmin etmək məqsədilə qoyulur. Pozulması yedəklənməyə səbəb ola bilər.'
  },
  {
    id: 'pr7',
    code: '3.28',
    name: 'Durmaq qadağandır',
    category: 'prohibitory',
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/f/f5/Zeichen_286.svg/240px-Zeichen_286.svg.png',
    meaning: '5 dəqiqədən artıq dayanmaq qadağandır. Qısa müddətli durmaq olar.',
    application: 'Mərkəzi küçələr, intensiv trafik olan yollar.',
    specialCases: 'Sərnişin endirmək və mindirmək üçün qısa dayanma icazəlidir.',
    examImportance: 'medium',
    commonMistake: true,
    detailedDescription: 'Bu nişan uzun müddətli dayanmağı qadağan edir, ancaq qısa müddət (adətən 3-5 dəqiqə) dayanıb sərnişin endirmək olar.'
  },
  {
    id: 'pr8',
    code: '3.1',
    name: 'Giriş qadağandır',
    category: 'prohibitory',
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/3/35/Zeichen_267.svg/240px-Zeichen_267.svg.png',
    meaning: 'Bütün nəqliyyat vasitələrinin bu istiqamətdə girişini qadağan edir.',
    application: 'Birtərəfli yolların əks istiqamətində.',
    specialCases: 'Yolun əks tərəfindən hərəkət ola bilər (birtərəfli yol).',
    examImportance: 'high',
    commonMistake: true,
    detailedDescription: 'Xalq arasında "Kirpiç" kimi tanınan bu nişan, həmin istiqamətdə hərəkətin tamamilə qadağan olunduğunu bildirir. Sürücü alternativ yollardan istifadə etməlidir.'
  },
  {
    id: 'pr9',
    code: '3.19',
    name: 'Geriyə dönmək qadağandır',
    category: 'prohibitory',
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/4/4b/Zeichen_272.svg/240px-Zeichen_272.svg.png',
    meaning: 'Bu kəsişmədə və ya yol hissəsində geriyə dönməni (U-turn) qadağan edir.',
    application: 'Dar yollarda, intensiv kəsişmələrdə.',
    specialCases: 'Sola dönmək icazəlidir (əgər başqa qadağa yoxdursa).',
    examImportance: 'high',
    commonMistake: true,
    detailedDescription: 'Bu nişan yalnız geriyə dönməni qadağan edir. Sola dönmək üçün maneə yoxdursa, sola dönmək olar.'
  },

  // Mandatory Signs (Məcburi nişanlar)
  {
    id: 'm1',
    code: '4.1',
    name: 'Hərəkət yalnız düz',
    category: 'mandatory',
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/3/3f/Zeichen_209-10.svg/240px-Zeichen_209-10.svg.png',
    meaning: 'Hərəkət yalnız düz istiqamətdə icazəlidir.',
    application: 'Kəsişmələrdə, ayrıcı zonaların başlanğıcında.',
    specialCases: 'Sağa və ya sola dönmək qadağandır.',
    examImportance: 'high',
    commonMistake: false,
    detailedDescription: 'Göy dairə içində ağ ox vasitəsilə icazə verilən hərəkət istiqaməti göstərilir. Bu nişanı pozaraq dönmək qanun pozuntusudur.'
  },
  {
    id: 'm2',
    code: '4.2',
    name: 'Hərəkət yalnız sağa',
    category: 'mandatory',
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/f/f4/Zeichen_209-20.svg/240px-Zeichen_209-20.svg.png',
    meaning: 'Hərəkət yalnız sağa dönərək davam etməlidir.',
    application: 'Birtərəfli yollara keçiddə, xüsusi istiqamətləndirmə tələb olunan yerlərdə.',
    specialCases: 'Düz və ya sola getmək olmaz.',
    examImportance: 'high',
    commonMistake: false,
    detailedDescription: 'Məcburi sağa dönmə nişanı sürücünü yalnız sağ istiqamətə hərəkət etməyə məcbur edir.'
  },
  {
    id: 'm3',
    code: '4.3',
    name: 'Hərəkət yalnız sola',
    category: 'mandatory',
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/5/54/Zeichen_209-30.svg/240px-Zeichen_209-30.svg.png',
    meaning: 'Hərəkət yalnız sola dönərək davam etməlidir.',
    application: 'Kəsişmələrdə sola dönmə məcburiyyəti olan yerlərdə.',
    specialCases: 'Düz və ya sağa getmək olmaz.',
    examImportance: 'high',
    commonMistake: false,
    detailedDescription: 'Bu nişan görünəndə yalnız sola dönmək icazəlidir, digər istiqamətlər qadağandır.'
  },
  {
    id: 'm4',
    code: '4.5',
    name: 'Dairəvi hərəkət',
    category: 'mandatory',
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/6/6c/Zeichen_215.svg/240px-Zeichen_215.svg.png',
    meaning: 'Dairəvi meydanda hərəkət yalnız oxların istiqamətində icazəlidir.',
    application: 'Dairəvi hərəkət təşkil olunan meydanların girişində.',
    specialCases: 'Saat əqrəbi istiqamətində hərəkət etmək qadağandır.',
    examImportance: 'high',
    commonMistake: true,
    detailedDescription: 'Dairəvi hərəkətə daxil olarkən sola gedənlərə üstünlük vermək lazımdır. Hərəkət saat əqrəbinin əksinə olur.'
  },
  {
    id: 'm5',
    code: '4.8',
    name: 'Velosiped yolu',
    category: 'mandatory',
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/7/70/Zeichen_237.svg/240px-Zeichen_237.svg.png',
    meaning: 'Bu yol yalnız velosipedlər üçün nəzərdə tutulub.',
    application: 'Ayrılmış velosiped yolları, parklar.',
    specialCases: 'Avtomobillərin hərəkəti qadağandır.',
    examImportance: 'medium',
    commonMistake: false,
    detailedDescription: 'Velosiped yoluna digər nəqliyyat vasitələrinin daxil olması qəti qadağandır.'
  },

  // Information Signs (İnformasiya nişanları)
  {
    id: 'i1',
    code: '5.1',
    name: 'Avtomobil yolu',
    category: 'information',
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/f/f6/Zeichen_330.svg/240px-Zeichen_330.svg.png',
    meaning: 'Avtomobil yolunun (avtostrada) başlandığını bildirir.',
    application: 'Avtomagistralların başlanğıcında.',
    specialCases: 'Minimum sürət 60 km/s, piyada hərəkəti qadağandır.',
    examImportance: 'high',
    commonMistake: false,
    detailedDescription: 'Avtomobil yolu yüksək sürətli hərəkət üçün nəzərdə tutulub. Traktor, at arabası, velosiped və piyada hərəkəti qadağandır.'
  },
  {
    id: 'i2',
    code: '5.2',
    name: 'Avtomobil yolunun sonu',
    category: 'information',
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/8/8a/Zeichen_331.svg/240px-Zeichen_331.svg.png',
    meaning: 'Avtomobil yolunun bitdiyini bildirir.',
    application: 'Avtomagistralın son hissəsində.',
    specialCases: 'Normal yol qaydaları tətbiq olunur.',
    examImportance: 'medium',
    commonMistake: false,
    detailedDescription: 'Bu nişandan sonra adi yol rejimi başlayır və sürət məhdudiyyətləri dəyişir.'
  },
  {
    id: 'i3',
    code: '5.3',
    name: 'Birtərəfli yol',
    category: 'information',
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/a/aa/Zeichen_220.svg/240px-Zeichen_220.svg.png',
    meaning: 'Yolda hərəkət yalnız bir istiqamətdədir.',
    application: 'Birtərəfli küçələrin başlanğıcında.',
    specialCases: 'Əks istiqamətdə hərəkət qəti qadağandır.',
    examImportance: 'high',
    commonMistake: false,
    detailedDescription: 'Birtərəfli yolda əks istiqamətdə hərəkət ciddi cərimələnir və qəza riski yaradır.'
  },
  {
    id: 'i4',
    code: '5.16',
    name: 'Dayanacaq',
    category: 'information',
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/5/52/Zeichen_314.svg/240px-Zeichen_314.svg.png',
    meaning: 'Nəqliyyat vasitələri üçün dayanacaq yeri.',
    application: 'Təşkil edilmiş dayanacaq məntəqələri.',
    specialCases: 'Dayanacaq qaydalarına riayət etmək lazımdır.',
    examImportance: 'low',
    commonMistake: false,
    detailedDescription: 'Dayanacaq yerində vasitəni səliqə ilə və digər avtomobillərə mane olmayacaq şəkildə yerləşdirmək lazımdır.'
  },
  {
    id: 'i5',
    code: '5.19',
    name: 'Dalan',
    category: 'information',
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/6/67/Zeichen_357.svg/240px-Zeichen_357.svg.png',
    meaning: 'Yolun keçid imkanı olmayan (kor) hissəsini bildirir.',
    application: 'Çıxışı olmayan küçələrin girişində.',
    specialCases: 'Daxil olmaq olar, lakin qarşı tərəfdən çıxış yoxdur.',
    examImportance: 'medium',
    commonMistake: false,
    detailedDescription: 'Dalan nişanı sürücüyə yolun sonunun bağlı olduğunu xəbər verir, belə ki, geri qayıtmaq üçün geriyə dönməli olacaqsınız.'
  },

  // Service Signs (Xidmət nişanları)
  {
    id: 's1',
    code: '6.1',
    name: 'Yanacaqdoldurma stansiyası',
    category: 'service',
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/c/c8/Zeichen_361-50.svg/240px-Zeichen_361-50.svg.png',
    meaning: 'Yaxınlıqda yanacaq stansiyası olduğunu göstərir.',
    application: 'Yanacaq stansiyasına 1-2 km qalmış.',
    specialCases: 'Məsafə əlavə lövhədə göstərilə bilər.',
    examImportance: 'low',
    commonMistake: false,
    detailedDescription: 'Uzun səfərlərdə yanacaq stansiyası nişanlarına diqqət etmək əhəmiyyətlidir.'
  },
  {
    id: 's2',
    code: '6.2',
    name: 'Texniki xidmət',
    category: 'service',
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/3/3f/Zeichen_363.svg/240px-Zeichen_363.svg.png',
    meaning: 'Avtomobil təmiri və texniki xidmətin olduğunu bildirir.',
    application: 'Avtoservis yaxınlığında.',
    specialCases: 'Təcili təmir ehtiyacı zamanı faydalıdır.',
    examImportance: 'low',
    commonMistake: false,
    detailedDescription: 'Texniki xidmət nişanı sərnişinlərə ən yaxın servis mərkəzini göstərir.'
  },
  {
    id: 's3',
    code: '6.4',
    name: 'Xəstəxana',
    category: 'service',
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/f/f3/Zeichen_358.svg/240px-Zeichen_358.svg.png',
    meaning: 'Yaxınlıqda xəstəxana və ya tibb məntəqəsi var.',
    application: 'Xəstəxanaya gedən yollarda.',
    specialCases: 'Təcili hallarda istifadə üçün.',
    examImportance: 'low',
    commonMistake: false,
    detailedDescription: 'Xəstəxana nişanı təcili tibbi yardım lazım olan hallarda istiqamət verir.'
  },
  {
    id: 's4',
    code: '6.7',
    name: 'Telefon',
    category: 'service',
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/d/d3/Zeichen_365-53.svg/240px-Zeichen_365-53.svg.png',
    meaning: 'İctimai telefon olduğunu bildirir.',
    application: 'Telefon qutularının yaxınlığında.',
    specialCases: 'Təcili zəng üçün istifadə edilə bilər.',
    examImportance: 'low',
    commonMistake: false,
    detailedDescription: 'Telefon nişanı əlaqə vasitələrinə çıxış imkanını göstərir.'
  },

  // Additional Signs (Əlavə nişanlar)
  {
    id: 'a1',
    code: '7.1',
    name: 'Məsafə',
    category: 'additional',
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/b/ba/Zusatzzeichen_1004-30.svg/240px-Zusatzzeichen_1004-30.svg.png',
    meaning: 'Əsas nişanın təsir məsafəsini göstərir.',
    application: 'Digər nişanların altında əlavə məlumat kimi.',
    specialCases: 'Məsafə metr və ya kilometrlə göstərilir.',
    examImportance: 'low',
    commonMistake: false,
    detailedDescription: 'Əlavə nişan əsas nişanın təsir dairəsini və ya məsafəsini dəqiqləşdirir.'
  },
  {
    id: 'a2',
    code: '7.4',
    name: 'Vaxt məhdudiyyəti',
    category: 'additional',
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/8/8e/Zusatzzeichen_1040-30.svg/240px-Zusatzzeichen_1040-30.svg.png',
    meaning: 'Nişanın yalnız göstərilən vaxt aralığında qüvvədə olduğunu bildirir.',
    application: 'Vaxtla məhdudlaşdırılmış qadağaların yanında.',
    specialCases: 'Göstərilən vaxtdan kənarda qadağa yoxdur.',
    examImportance: 'medium',
    commonMistake: true,
    detailedDescription: 'Vaxt məhdudiyyəti adətən dayanma, sürət və digər məhdudiyyətlərə tətbiq olunur.'
  },
  {
    id: 'a3',
    code: '7.5',
    name: 'Nəqliyyat növü',
    category: 'additional',
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/3/37/Zusatzzeichen_1048-10.svg/240px-Zusatzzeichen_1048-10.svg.png',
    meaning: 'Nişanın yalnız müəyyən növ nəqliyyata aid olduğunu göstərir.',
    application: 'Seçici məhdudiyyətlər tətbiq edən yerlərdə.',
    specialCases: 'Yalnız göstərilən nəqliyyat növlərinə aiddir.',
    examImportance: 'low',
    commonMistake: false,
    detailedDescription: 'Bu əlavə nişan hansı növ nəqliyyat vasitələrinin təsir altında olduğunu müəyyən edir.'
  }
]
